### PR TITLE
Fix bug when checking if device has been allocated

### PR DESCRIPTION
**Pull request by M1Sports20**
I don't care if you pull in this MR or you just make the change on your side.  I wanted to show you this though.

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Thanks!

**Comment by M1Sports20** [comment]
You actually got to it too soon. I believe in C you can just not do the memset

**Comment by tzarc** [comment]
I'd prefer to keep it in for clarity. Will make the changes on my end.

**Comment by tzarc** [comment]
Actually, the initialiser is already set to zero -- you're correct, no need at all.

**Pull request merged**
