### PR TITLE
Adding implementation of angled lines

### PR DESCRIPTION
**Pull request by Gr1mR3aver**
## Description

Added implementation of angled line drawing using Bresenham's algorithm.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [ ] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

### CODE REVIEW

**Review by tzarc — APPROVED** [review]

**Comment by tzarc** [comment]
Thanks!

**Comment by Gr1mR3aver** [comment]
I have an implementation for drawing circles as well that I could add.  Considering writing one for elipses as well if you are interested.

Additionally have a driver written for the sr7735r chip (used on the adafruit 1.8" TFT boards) , but haven't been able to test it yet. I based it. Off the one you wrote for the ili9xxx since many of the opcodes are the same. The ST7735r uses an external pwm signal for the backlight, and the opcode set is simplified. Planning to hold off checking in until I receive my bits and pieces and I am able to test, but I can put it in now if you like.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tzarc** [comment]
Feel free to make a PR for each of the changes -- I've got two ST7735's on my desk already.

**Comment by Gr1mR3aver** [comment]
Will do.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
