### PR TITLE
Draft: Mono2 and SSD drivers

### PR DESCRIPTION
**Pull request by M1Sports20**
This is far from ready, but wanted to give you something to show progress and to show you where I have been going.  Not expecting this to be merged.

Remaining Tasks:
- [x] Add I2C support
- [x] SSD1306 support
- [ ] Add dirty region support when updating OLED display
- [ ] Maybe move SSD buffer format out of mono2 fb and leave it in the SSD drivers. (Slow down display update)
- [ ] Fix TODOs
- [ ] General formating and cleanup

### CODE REVIEW

**Comment by M1Sports20** [comment]
@tzarc I don't' know how github's Draft PRs notify you, so I am just tagging you

**Comment by M1Sports20** [comment]
I am removing the sh1106 driver and just creating a ssd driver.  For the functionality at the moment I don't see a reason to have separate drivers.

**Comment by M1Sports20** [comment]
I am getting a friend to test SSD1306, will update.

**Comment by tzarc** [comment]
Just a note:

> Images, Add support for more than 1bpp. (downscale)

This isn't really relevant -- 1bpp should be selected at the time of conversion. The QMK CLI commands handle this already.

**Comment by M1Sports20** [comment]
I am getting a friend to test SSD1306, will update.

> Just a note:
> 
> > Images, Add support for more than 1bpp. (downscale)
> 
> This isn't really relevant -- 1bpp should be selected at the time of conversion. The QMK CLI commands handle this already.

True, I think its overkill if i do it.

**Comment by M1Sports20** [comment]
I am getting there, sorry got delayed.  Let me know if you are on a timline.  I am trying to get a friend to test out SSD1306 on I2C

**Comment by tzarc** [comment]
> 
> 
> I am getting there, sorry got delayed. Let me know if you are on a timline. I am trying to get a friend to test out SSD1306 on I2C

No issue at all -- this stuff is decoupled enough from each other so if Quantum Painter gets merged into QMK it can do so without your OLED stuff... if that happens you could then target mainline QMK for the PR instead. Currently no intended timeframe -- it's in review.

**Pull request closed without merging**
